export enum ORDER_STATUS {
    INPROCESS = 'INPROCESS',
    ACCEPETED = 'ACCEPETED',
    REJECTED = 'REJECTED',
}

export enum ORDER_STAGE {
    ONBOARD = 'INPROCESS',
    INWAY = 'INWAY',
    DELIVERED = 'DELIVERED',
}